### PR TITLE
Update documentation for Arch Linux

### PR DESCRIPTION
**Pull request by Nuc1eoN**
Arch Linux has out of the box for Solo and a dedicated wiki page which I have linked.

Also fixed an incorrect systemd command.

### CODE REVIEW

**Comment by nickray** [comment]
Oh wow, neat! Wasn't aware of that page. As an Arch user, I'm not sure it needs to be listed as "recent" distribution hehe, but gotcha, thanks!

**Comment by nickray** [comment]
@all-contributors, add @Nuc1eoN for docs

**Comment by nickray** [comment]
@allcontributors, add @Nuc1eoN for doc

**Comment by nickray** [comment]
Hmm, the bot seems sleepy, sorry about that :/

**Comment by Nuc1eoN** [comment]
Hehe nvm :D Maybe in the future I can help with more than the documentation^^

**Pull request merged**
