### PR TITLE
Add black to travis checking

### PR DESCRIPTION
**Pull request by pjz**
Black was already in the Makefile, I just added a `blackcheck` target that checks but doesn't reformat, and added it to the `test` target it so that it would be called by travis.

### CODE REVIEW

**Comment by yparitcher** [comment]
already done in #51 (although with slightly different implementation)

**Comment by pjz** [comment]
Yeah, but #51 isn't merged yet - and it's been out there a while.  I was thinking it might help to break out this one piece and get it merged separately.

**Comment by conorpp** [comment]
Yeah I think merging in smaller steps generally will be easier.  Sorry for the delays, will try to be more prompt in future.

**Comment by conorpp** [comment]
Thanks!

**Pull request merged**
