### PR TITLE
refactor a bit

### PR DESCRIPTION
**Pull request by conorpp**
This adds some more tests and refactors previous tests to `ctap_test.py` script.

### CODE REVIEW

**Comment by nickray** [comment]
Will have a proper look, haven't dug into this part of the code before.

**Comment by nickray** [comment]
1. - "Check busy interleaved" doesn't finish (in hid)
2. - I guess it's intended to be used with silent authnr build?
3. - it's a bit "very long file", but better to merge now and refactor later
4. - does this capture all/most of the interoperability testing?

**Comment by conorpp** [comment]
This captures nearly all of the testing done by the FIDO conformance tests, plus some more tests.  For the "Check busy interleaved", was this in simulation or real?

**Comment by nickray** [comment]
in real, regular hacker build

**Comment by conorpp** [comment]
should work now

**Pull request merged**
