### PR TITLE
Added OsX arm install, updated FIDO2 test site links

### PR DESCRIPTION
**Pull request by Wesseldr**
Improving and updating documentation of nucleo32 for current version.

### CODE REVIEW

**Comment by nickray** [comment]
Cool, thanks! Have you by chance tested whether builds via homebrew arm-gcc work? Asking because the Debian/Ubuntu version is broken (this is also why we send people to ARM site to download, instead of apt). Not a Mac person myself, I can imagine homebrew simply automates doing that (instead of repackaging and introducing bugs like the otherwise good folk from Debian).

**Comment by Wesseldr** [comment]
I can confirm builds run fine on OsX with the brew arm compiler. But I'm not sure 'which' build you're asking for. I dont have a Solo Hacker si I have not tested that.

_Can I reflash a Solo secure and flash it back to a hacker? Even if that means brutal like connecting wires to the solo?_

I can flash the build into an STM32L432 board and it becomes a Solo hacker key. 

**Solo for Hackers build**
```bash
✅make cbor
✅make build-hacker
   text	   data	    bss	    dec	    hex	filename
  58268	    368	  26984	  85620	  14e74	solo.elf
arm-none-eabi-objcopy -O ihex solo.elf solo.hex
solo mergehex solo.hex bootloader.hex all.hex
merging <intelhex.IntelHex object at 0x103a49f10> with bootloader.hex

cd ../..
🤔make venv
python3 -m venv venv
venv/bin/pip -q install --upgrade pip
venv/bin/pip -q install --upgrade -r tools/requirements.txt
**ERROR:** solo-python 0.0.11 has requirement fido2==0.6.0, but you'll have fido2 0.7.0 which is incompatible.
venv/bin/pip -q install --upgrade black
`
Although the error on the fido2 lib it compiles fine. (can we change the requirement and upgrade it to 0.7.0 ?)

✅source venv/bin/activate
(I don't have a solo hacker here, so using the programmed STM32L432 for testing)
✅solo program aux enter-bootloader
solo program aux enter-bootloader
Solo rebooted.  Reconnecting...
.... some exception stuff probably from the rebooting key..
solo.exceptions.NoSoloFoundError: no Solo found
✅solo program bootloader targets/stm32l432/solo.hex
Not using FIDO2 interface.
erasing firmware...
updated firmware 100%             
time: 6.88 s
```
**Developing Solo (No Hardware Needed)**

```bash
✅make all
Only these warnings, rest all compiles ok
fido2/ctap.c:470:53: warning: too many arguments in call to 'ctap2_user_presence_test'
    but = ctap2_user_presence_test(CTAP2_UP_DELAY_MS);
          ~~~~~~~~~~~~~~~~~~~~~~~~                  ^
fido2/ctap.c:708:56: warning: too many arguments in call to 'ctap2_user_presence_test'
        if (!ctap2_user_presence_test(CTAP2_UP_DELAY_MS))
             ~~~~~~~~~~~~~~~~~~~~~~~~                  ^
fido2/ctap.c:1144:56: warning: too many arguments in call to 'ctap2_user_presence_test'
        if (!ctap2_user_presence_test(CTAP2_UP_DELAY_MS))
             ~~~~~~~~~~~~~~~~~~~~~~~~                  ^
fido2/ctap.c:1652:59: warning: too many arguments in call to 'ctap2_user_presence_test'
            if (ctap2_user_presence_test(CTAP2_UP_DELAY_MS))
                ~~~~~~~~~~~~~~~~~~~~~~~~                  ^

✅pip install -r tools/requirements.txt
✅./main
[DEBUG] Using UDP backing
state file does not exist, creating it
[STOR] Auth state is NOT initialized.  Initializing..
state file exists
[STOR] pin not set.
```
Running the test suite in --sim mode does give quite some errors and a reboot of the software key let the rest of the tests fail. But that might be expected behaviour....
```
 python -m pytest tests/standard --sim
=============================================================================================================================== test session starts ===============================================================================================================================
platform darwin -- Python 3.7.3, pytest-4.3.1, py-1.8.0, pluggy-0.9.0
rootdir:/tmp/fido2-tests, inifile:
plugins: remotedata-0.3.1, openfiles-0.3.2, doctestplus-0.3.0, arraydiff-0.3
collected 118 items                                                                                                                                                                                                                                                               

tests/standard/connect_test.py .                                                                                                                                                                                                                                            [  0%]
tests/standard/fido2/test_ctap1_interop.py ...                                                                                                                                                                                                                              [  3%]
tests/standard/fido2/test_get_assertion.py ....................E                                                                                                                                                                                                            [ 21%]
tests/standard/fido2/test_getinfo.py EEEEEE                                                                                                                                                                                                                                 [ 26%]
tests/standard/fido2/test_make_credential.py EEEEEEEEEEEEEEE^C
here a lot of test start to fail, the other side just got a:
[DEBUG] MAGIC REBOOT command recieved!
```

If I run these tests against my official Solo secure key lot of them fail as well so that could be more an osx thing than these build.

Connecting a serial to the solo-key hacker (STM32L432) still doesn't work for me since OsX has no udev rules and I haven't figured out how to work around that.. I do however have a serial usb device when I connect the STM32.

Hope this answers your question about the build or at least give you a good view of what's working now and whats not.

**Comment by nickray** [comment]
No you can't revert to Hacker from Secure, ROP level 2 is activated which is irreversible.

**Comment by Wesseldr** [comment]
Can some one please merge this one if it all green lights :-)

**Comment by conorpp** [comment]
Thanks @Wesseldr!

Regarding the tests, since it looks like you're running them locally, you need to run like this.

```
# in project root
./tools/test_sw_token.sh
```

`test_sw_token.sh` will restart the `main` program when it "reboots".  Otherwise `main` just exits and the rest of the tests fail.
```

**Comment by Wesseldr** [comment]
> Regarding the tests, since it looks like you're running them locally, you need to run like this.
> 
> ```
> # in project root
> ./tools/test_sw_token.sh
> ```
> 
> `test_sw_token.sh` will restart the `main` program when it "reboots". Otherwise `main` just exits and the rest of the tests fail.

Yes!!! all tests work fine now on OsX

----
Just currently testing it on Ubuntu Desktop 18.10 
After installing anaconda python and 
```
sudo apt-get install gcc-arm-none-eabi
```
It compiles fine and all tests run correct

**Pull request merged**
