### PR TITLE
Describe running Solo on the Nucleo board

### PR DESCRIPTION
**Pull request by szszszsz**
Provide description about running and testing Solo firmware on the [STM32 Nucleo] board.

Please review. Perhaps the place to link it is in `building.md`, rather than in a global menu.

[STM32 Nucleo]: https://www.st.com/en/evaluation-tools/stm32-mcu-nucleo.html?querycriteria=productId=LN1847

### CODE REVIEW

**Comment by szszszsz** [comment]
Removed copyrights line from commits altogether. Included PRs done by @Wesseldr.

**Comment by szszszsz** [comment]
Might be slightly outdated since January write. Was working back then with my Nucleo32 board. Seems to be confirmed working by @Wesseldr in https://github.com/solokeys/solo/issues/235#issuecomment-518038322.

**Comment by szszszsz** [comment]
Automatic review reports whitespace issues. Could anyone volunteer to correct that? I do not have any spare time at the moment.

**Comment by nickray** [comment]
Thanks for fixing this @szszszsz. Codacy is a bit over-zealous ;)

**Comment by Wesseldr** [comment]
Fixed Codacy/PR Quality Review block for this PR#65 with PR #236, please note that this #65 has 2 files changed so do not completely delete this one.

**Comment by h0rac** [comment]
I followed the guide to run solo key on Nucleo STM32L432KC but it doesn't work...I would like to know what I'm doing wrong.  I see red LED flash but it is not presenting as solo key

➜  stm32l432 git:(master) ✗ solo ls
:: Solos

Screenshot 2020-02-18 at 19 47 27

**Pull request merged**
