### PR TITLE
Cleaned nucleo32-board.md

### PR DESCRIPTION
**Pull request by Wesseldr**
The original pull request #65 was not completely compliant. hopefully this one is.

### CODE REVIEW

**Comment by szszszsz** [comment]
Please let me know, when you finish - I will add then resulting commits (with your name) to the original #65 PR.

**Comment by Wesseldr** [comment]
Sure, I'll let you know for now digging through 140 items... get most fixed with Atom now the picky ones I'm working on

**Comment by Wesseldr** [comment]
Done! it's cleaned up!

**Comment by szszszsz** [comment]
Great! Will merge there in a minute, and mention the status here.

**Comment by nickray** [comment]
Oh. Just merged the original one. Can I merge this on top?

**Comment by Wesseldr** [comment]
Yes should be a problem overwrite it.

**Comment by nickray** [comment]
Apologies for leaning on you, but can you perhaps rebase your branch on top of current master?

**Comment by Wesseldr** [comment]
Let's see if this works out ....

**Comment by nickray** [comment]
Seems to be the case! Thanks!

**Comment by nickray** [comment]
Just compared before/after, looks nicer indeed (aka not just busy work to please Codacy). Thanks again.

**Comment by Wesseldr** [comment]
YW, glad I could help.

**Comment by nickray** [comment]
@all-contributors add Wesseldr for doc

**Pull request merged**
