### PR TITLE
Udev rules related docs update

### PR DESCRIPTION
**Pull request by szszszsz**
A couple of corrections regarding Udev rules documentation.
Added an Udev rule to symlink to the serial port.

Work in progress - testing connection to serial to be exact.

### CODE REVIEW

**Comment by szszszsz** [comment]
For some reason with this Udev rules I still cannot access the symlinked serial as an user.

**Comment by szszszsz** [comment]
Please review the changes.

**Comment by yparitcher** [comment]
please add this to the udev rule this instead of stopping ModemManager:
```
ACTION!="add|change|move", GOTO="mm_usb_device_blacklist_end"
SUBSYSTEM!="usb", GOTO="mm_usb_device_blacklist_end"
ENV{DEVTYPE}!="usb_device",  GOTO="mm_usb_device_blacklist_end"

ATTRS{idVendor}=="0483", ATTRS{idProduct}=="a2ca", ENV{ID_MM_DEVICE_IGNORE}="1"

LABEL="mm_usb_device_blacklist_end"
```

**Comment by szszszsz** [comment]
Corrected as suggested.

**Comment by szszszsz** [comment]
Connected: #45

**Comment by conorpp** [comment]
Everything looks great, sorry for delay.  Thank you!!

**Pull request merged**
