### PR TITLE
Nfc testing

### PR DESCRIPTION
**Pull request by merlokk**
NFC works

### CODE REVIEW

**Comment by conorpp** [comment]
Great, so this bridges all of the tests to NFC?  How have you tested?  Did you use with all of the tests? E.g. `u2f fido2 rk`?

**Comment by merlokk** [comment]
u2f and rk works  with yubikey
fido2 works with yubikey but not all tests passed because yubikey returns different results than solokey

solokey works, but with changes in library. Now solo-library dont support fido2 v.0,7.0 im looking how to add this into solo-python.

**Comment by conorpp** [comment]
Great, thank you!  Can you open an issue with the tests that differ between Yubikey and Solo?

**Comment by merlokk** [comment]
needs to add extended length apdu to solokey or (for test) patch library.

yes, ill create the issue

**Pull request merged**
