### PR TITLE
Tests refactoring

### PR DESCRIPTION
**Pull request by szszszsz**
I have started cleaning up the Python's tests. Here is a first set of modifications. 
Let me know what you think.

Further I plan to rewrite it in pytest to give it better handling.

### CODE REVIEW

**Comment by nickray** [comment]
+1 for pytest

**Comment by conorpp** [comment]
I think the refactoring is great so far.  I think there's a lot of testing for FIDO2 that could be added to what we have so far.  FIDO has a pretty nice test tool for FIDO2 and is pretty descriptive for each test that runs (written by @herrjemand).  Passing it is a requirement for certification.  You can request to [download it here](https://fidoalliance.org/tool-request-agreement/).

It'd be great to implement some of the same checks this tool does.

**Comment by conorpp** [comment]
Sorry I took awhile to get to this.  There are a number of conflicts now I'm not confident in fixing.  Could you take a look?

**Comment by szszszsz** [comment]
Sorry for delay! Will do! I should be back this week.

**Comment by nickray** [comment]
@szszszsz , things have changed a little in the meantime...

You should probably rebase onto master manually.

Specifically:
- Yubico python-fido2 is (soon to be) gone
- UDP transport exists as monkey patch via `solo-python`
- It would be nice to have the entire CTAP suite of tests in `solo-python`, either as sub-command of `solo` or as separate command.

**Comment by nickray** [comment]
@szszszsz https://github.com/solokeys/fido2-tests makes this inapplicable :/

If you have input on the general structure, can your share there?

**Comment by szszszsz** [comment]
Yes. Shame I have not finished that earlier. Good idea to move the tests out - will look there.

**Pull request closed without merging**
