### PR TITLE
Document application ideas

### PR DESCRIPTION
**Pull request by jolo1581**
Hello,

I added a new section with ideas around Solo.
Please review and give me feedback.

### CODE REVIEW

**Comment by szszszsz** [comment]
> Please resubmit (and close this PR)

About this, the branch can be force-pushed with changes, no need to create noise with additional PRs.

**Comment by jolo1581** [comment]
I will correct it this weekend.

Thanks for feedback.

**Comment by jolo1581** [comment]
Reworked by forced Push, please review again

**Comment by nickray** [comment]
Thanks!

**Pull request merged**
